{
 "title": "Adventure2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "game", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "http://host.docker.internal:3001/api/game/$game",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Forge Heat",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forge_heat{location=\"blacksmith\", game_id=\"$game\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forge Heat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "forge_heat{location=\"blacksmith\", game_id=\"$game\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swords",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swords{game_id=\"$game\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Holy Sword",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "holy_sword{game_id=\"$game\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evil Sword",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evil_sword{game_id=\"$game\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server-Wide: Active Games",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "root_selector": "table",
     "source": "url",
     "type": "json",
     "url": "http://host.docker.internal:3001/api/cache",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Quest Log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{service_name=\"adventure\"} != `failed` | game_id=\"$game\" | label_format level=detected_level"
    }
   ]
  },
  {
   "title": "Forge Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{service_name=\"forge\"} | game_id=\"$game\""
    }
   ]
  }
 ]
}