{
 "title": "Tableau de bord du jeu d'aventure",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chaleur de la forge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forge_heat{location=\"blacksmith\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chaleur de la forge",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "forge_heat{location=\"blacksmith\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Épées",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "swords", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Épée sainte",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "holy_sword", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Épée maléfique",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "evil_sword", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Chronologie des épées",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 7 },
   "targets": [
    { "expr": "evil_sword", "legendFormat": "__auto" },
    { "expr": "holy_sword", "legendFormat": "__auto" },
    { "expr": "swords", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Journal des quêtes",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{service_name=\"adventure\"} != `failed` | label_format level=detected_level"
    }
   ]
  }
 ]
}