{
 "title": "Game Admin Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "game", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Server-Wide: Active Games",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "root_selector": "table",
     "source": "url",
     "type": "json",
     "url": "http://host.docker.internal:3001/api/cache",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Swords (All Games)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(swords{}[1h]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Holy Swords (All Games)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(swords{}[1h]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evil Swords (All Games)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(evil_swords{}[1h]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Forge Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{service_name=\"forge\"} "
    }
   ]
  }
 ]
}