apiVersion: 1
datasources:
- name: loki
  type: loki
  access: proxy
  url: http://loki:3100
- name: prometheus
  type: prometheus
  url: http://prometheus:9090
  jsonData:
    prometheusType: Prometheus
    prometheusVersion: 2.50.0
    cacheLevel: 'None'
    timeInterval: 3s
- name: tempo
  type: tempo
  url: "http://tempo:3200"
  jsonData:
    nodeGraph: 
      enabled: true
    serviceMap:
      datasourceUid: 'prometheus'
    tracesToLogsV2:
      datasourceUid: 'loki'
    tracesToMetrics:
      datasourceUid: 'prometheus'
- name: infinity
  type: yesoreyeram-infinity-datasource
  basicAuth: false
